<?php

return [
    "anderer",
    "unseres",
    "keinem",
    "jener",
    "jenes",
    "keiner",
    "jedem",
    "anders",
    "da",
    "nichts",
    "sehr",
    "unseren",
    "den",
    "kein",
    "wie",
    "zu",
    "meine",
    "sondern",
    "ihm",
    "bei",
    "einige",
    "wollen",
    "denn",
    "ihres",
    "werde",
    "viel",
    "wenn",
    "eines",
    "uns",
    "welchem",
    "habe",
    "können",
    "mich",
    "und",
    "euren",
    "dazu",
    "jedes",
    "kann",
    "an",
    "wir",
    "diesem",
    "was",
    "eure",
    "ihre",
    "wieder",
    "dann",
    "unser",
    "eurer",
    "in",
    "deine",
    "doch",
    "ist", "um", "demselben",
    "nach", "waren", "weil",
    "manchen", "dem", "ihn",
    "anderes", "ohne",
    "einen", "wollte", "jenem",
    "einiger", "seinen",
    "dessen", "jede", "mir",
    "keinen", "dasselbe",
    "könnte", "es", "hat",
    "oder", "über",
    "deines", "ihr", "wird",
    "desselben", "vor",
    "meiner", "seines", "manchem",
    "hatten", "einigem",
    "anderen", "einmal",
    "diese", "meines", "ich",
    "also", "derselben",
    "hinter", "solchem", "war",
    "damit", "einem", "deiner",
    "aus", "seinem", "aller",
    "anderm", "sein", "nur",
    "einig", "dieselbe", "solchen",
    "weg", "haben", "hin",
    "deinen", "dass", "einigen",
    "daß", "solche",
    "alle", "diesen", "im",
    "einiges", "du", "nicht",
    "zwischen", "würden", "das",
    "andere", "jenen",
    "sind", "die", "jetzt", "so",
    "dein", "vom", "bist",
    "dieser", "am", "dies", "des",
    "manche", "ihnen",
    "während", "allem", "indem",
    "aber", "musste", "dieselben",
    "eures", "gewesen", "ihrer",
    "welcher", "derselbe",
    "euer", "andern", "seiner",
    "dich", "denselben", "sie", "welchen",
    "dieses", "eurem", "unserem",
    "bis", "hier", "allen",
    "mancher", "wo", "einer",
    "auch", "gegen", "alles", "weiter",
    "nun", "keines", "keine",
    "meinen", "werden", "zwar",
    "der", "warst", "zur", "eine",
    "wirst", "ihren", "auf", "dir",
    "soll", "anderem", "als",
    "deinem", "durch", "von",
    "meinem", "jene", "ein",
    "mit", "unter", "zum", "bin", "hab",
    "derer", "jeden", "sollte",
    "würde", "welches",
    "ander", "er", "etwas",
    "sich", "manches", "welche", "seine",
    "jeder", "ins", "für",
    "solcher", "solches",
    "ihrem", "unsere", "will",
    "ob", "dort", "hatte", "mein", "sonst",
    "man", "muss", "noch",
    "machen", "selbst", "euch"
];
